import _ from 'lodash';
const arr = [
    {
        id: 1,
        name: '大宇三维打印',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: null,
        tb_user: [],
    },
    {
        id: 10000,
        name: '客户',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 1,
        tb_user: [],
    },
    {
        id: 20000,
        name: '技术部',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 1,
        tb_user: [],
    },
    {
        id: 30000,
        name: '泉州分公司',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 1,
        tb_user: [],
    },
    {
        id: 30001,
        name: '财务部',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 30000,
        tb_user: [],
    },
    {
        id: 30002,
        name: '业务部',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 30000,
        tb_user: [],
    },
    {
        id: 40000,
        name: '德化分公司',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 1,
        tb_user: [],
    },
    {
        id: 40001,
        name: '财务部',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 40000,
        tb_user: [],
    },
    {
        id: 40002,
        name: '业务部',
        is_depart: true,
        remark: '请填写备注说明!',
        parent_id: 40000,
        tb_user: [],
    },
    {
        id: 1000091,
        name: 'vip1',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 10000,
        tb_user: [
            {
                id: 1,
                name: '许鹏',
                password: '123456',
                tel: '15160315110',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
            {
                id: 12,
                name: '许12',
                password: '123456',
                tel: '15160315012',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
        ],
    },
    {
        id: 1000092,
        name: 'vip2',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 10000,
        tb_user: [
            {
                id: 1,
                name: '许鹏',
                password: '123456',
                tel: '15160315110',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
            {
                id: 12,
                name: '许12',
                password: '123456',
                tel: '15160315012',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
        ],
    },
    {
        id: 2000091,
        name: '主管',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 20000,
        tb_user: [
            {
                id: 1,
                name: '许鹏',
                password: '123456',
                tel: '15160315110',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
        ],
    },
    {
        id: 2000092,
        name: '职员',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 20000,
        tb_user: [
            {
                id: 1,
                name: '许鹏',
                password: '123456',
                tel: '15160315110',
                createdAt: '2025-06-26T17:11:16.051Z',
                address_info: [],
                contacts: [],
            },
        ],
    },
    {
        id: 3000191,
        name: '主管',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 30001,
        tb_user: [],
    },
    {
        id: 3000192,
        name: '职员',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 30001,
        tb_user: [],
    },
    {
        id: 3000291,
        name: '主管',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 30002,
        tb_user: [],
    },
    {
        id: 3000292,
        name: '职员',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 30002,
        tb_user: [],
    },
    {
        id: 4000191,
        name: '主管',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 40001,
        tb_user: [],
    },
    {
        id: 4000192,
        name: '职员',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 40001,
        tb_user: [],
    },
    {
        id: 4000291,
        name: '主管',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 40002,
        tb_user: [],
    },
    {
        id: 4000292,
        name: '职员',
        is_depart: false,
        remark: '请填写备注说明!',
        parent_id: 40002,
        tb_user: [],
    },
];

//使用lodash  获取下面的数据  封装成函数名tool_get_user_depart_role_list,参数是arr,返回值是result
const result = [
    {
        id: 1,
        name: '许鹏',
        password: '123456',
        tel: '15160315110',
        createdAt: '2025-06-26T17:11:16.051Z',
        address_info: [],
        contacts: [],
        depart_ids: [
            { id: 1, name: '大宇三维打印', is_depart: true, remark: '请填写备注说明!', parent_id: null },
            { id: 10000, name: '客户', is_depart: true, remark: '请填写备注说明!', parent_id: 1 },
            { id: 20000, name: '技术部', is_depart: true, remark: '请填写备注说明!', parent_id: 1 },
        ],
        role_list: [
            { id: 2000092, name: '职员', is_depart: false, remark: '请填写备注说明!', parent_id: 20000 },
            { id: 2000091, name: '主管', is_depart: false, remark: '请填写备注说明!', parent_id: 20000 }, //
            { id: 1000091, name: 'vip1', is_depart: false, remark: '请填写备注说明!', parent_id: 10000 },
            { id: 1000092, name: 'vip2', is_depart: false, remark: '请填写备注说明!', parent_id: 10000 },
        ],
    },
    {
        id: 12,
        name: '许12',
        password: '123456',
        tel: '15160315012',
        createdAt: '2025-06-26T17:11:16.051Z',
        address_info: [],
        contacts: [],
        depart_ids: [
            { id: 1, name: '大宇三维打印', is_depart: true, remark: '请填写备注说明!', parent_id: null },
            { id: 10000, name: '客户', is_depart: true, remark: '请填写备注说明!', parent_id: 1 },
        ],
        role_list: [
            { id: 1000092, name: 'vip2', is_depart: false, remark: '请填写备注说明!', parent_id: 10000 },
            { id: 1000091, name: 'vip1', is_depart: false, remark: '请填写备注说明!', parent_id: 10000 },
        ],
    },
];
